name: Run JavaScript Script

on:
  schedule:
    - cron: "*/1 * * * *"  # اجرای هر ۱ دقیقه

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # به‌روزرسانی به نسخه‌ی Node 18

      - name: Install dependencies
        run: npm install

      - name: Run JavaScript script
        run: node script.js
